config/routes.rb
Rails.application.routes.draw do

  get 'applications/setverified/:id' => 'applications#setverified'
  get 'applications/setattended/:id' => 'applications#setattended'
  get 'users/settype/:id' => 'users#settype'
  get '/projects/:id/direction' => 'projects#direction'
  get '/projects/:id/notice' => 'projects#notice'
  get 'users/check_available' => 'users#check_available'
  post '/user/login' => 'user#login'
  get '/user/logout' => 'user#logout'
  get '/user/manage' => 'user#manage'
  get '/residents/manage' => 'residents#manage'
  get '/projects/manage' => 'projects#manage'
  get '/nurses/manage' => 'nurses#manage'
  get '/users/manage' => 'users#manage'
  root :to => 'user#index'

  resources :pickup_sites, :residents, :nurses
  resources :rooms do
    resources :residents
  end
  resources :zones do
    resources :rooms
    resources :residents
  end

  resources :assignments, :records, :managements, :nursings, :applications 

  resources :projects do
    resources :applications, :assignments, :records
  end

  resources :nursing_homes do
    resources :managements, :projects, :zones, :rooms, :residents, :nurses, :nursings
  end

  resources :users do
    resources :applications, :messages
  end

  resources :messages

end

app/models/application.rb
class Application < ActiveRecord::Base
  belongs_to :user
  belongs_to :volunteer, class_name: "User", foreign_key: "user_id"
  belongs_to :project
  belongs_to :pickup_site
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def redirect_back_or_default(default = root_path, options = {})
    redirect_to (request.referer.present? ? :back : default), options
  end

  def validate_user_login
    if current_user.nil?
      flash[:error]="抱歉，您尚未登录。"
      respond_to do |format|
        format.html {redirect_back_or_default}
        format.json {render :text => ({:error=>flash[:error]}).to_json}
      end
    end
  end

  def validate_admin_login
    unless !current_user.nil? && current_user.admin?
      respond_to do |format|
        format.html do
          if request.xhr?
            flash.now[:error]="抱歉，您不是管理员！"
            render :text => "error_message_return:#{flash.now[:error]}"
          else
            flash[:error]="抱歉，您不是管理员！"
            redirect_back_or_default
          end
        end
        format.json {render :text => ({:error=>flash[:error]}).to_json}
      end
    end
  end

  def validate_director_login
    unless !current_user.nil? && current_user.director?
      respond_to do |format|
        format.html do
          if request.xhr?
            flash.now[:error]="抱歉，您不是组长！"
            render :text => "error_message_return:#{flash.now[:error]}"
          else
            flash[:error]="抱歉，您不是组长！"
            redirect_back_or_default
          end
        end
        format.json {render :text => ({:error=>flash[:error]}).to_json}
      end
    end
  end

  def validate_volunteer_login
    unless !current_user.nil? && current_user.volunteer?
      respond_to do |format|
        format.html do
          if request.xhr?
            flash.now[:error]="抱歉，您不是普通志愿者！"
            render :text => "error_message_return:#{flash.now[:error]}"
          else
            flash[:error]="抱歉，您不是管理员！"
            redirect_back_or_default
          end
        end
        format.json {render :text => ({:error=>flash[:error]}).to_json}
      end
    end
  end


  
  private
 
  # Finds the User with the ID stored in the session with the key
  # :current_user_id This is a common way to handle user login in
  # a Rails application; logging in sets the session value and
  # logging out removes it.
  def current_user
    @_current_user ||= session[:current_user_id] &&
      User.find_by_id(session[:current_user_id])
  end
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  before_action :set_application, only: [:show, :edit, :update, :destroy]
  before_filter :validate_user_login
  # GET /applications
  # GET /applications.json
  def index
    if params[:project_id].nil?
      @applications = Application.all
    else
      params[:offset] ||= 0
      params[:limit] ||= 1000
      @applications = Project.find_by_id(params[:project_id]).applications.order("id desc").offset(params[:offset]).limit(params[:count])
    end
  end

  # GET /applications/1
  # GET /applications/1.json
  def show
  end

  # GET /applications/new
  def new
    @application = Application.new
  end

  # GET /applications/1/edit
  def edit
  end

  # POST /applications
  # POST /applications.json
  def create
    #binding.pry
    @application = Application.new(application_params.merge({:user_id=>current_user.id}))

    respond_to do |format|
      if @application.save
        #format.html { redirect_to @application, notice: 'Application was successfully created.' }
        format.html { redirect_to controller: "projects", action: "direction", id: @application.project_id }
        format.json { 
          #render :text => "<a rel=\"nofollow\" href=\"/applications/#{@application.id}\" data-method=\"delete\" data-remote=\"true\" class=\"remote-applications-#{@application.id} btn btn-primary\">取消报名</a>" 
        }
      else
        format.html { render :new }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /applications/1
  # PATCH/PUT /applications/1.json
  def update
    respond_to do |format|
      if @application.update(application_params)
        format.html { redirect_to @application, notice: 'Application was successfully updated.' }
        format.json { render :show, status: :ok, location: @application }
      else
        format.html { render :edit }
        format.json { render json: @application.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /applications/1
  # DELETE /applications/1.json
  def destroy
    @application.destroy
    respond_to do |format|
      #format.html { redirect_to applications_url, notice: 'Application was successfully destroyed.' }
      format.json { 
        render :text =>"<button type=\"button\" class=\"btn btn-primary\" data-toggle=\"modal\" data-target=\"#myModal\">报名</button>"
        #render :text => "<a rel=\"nofollow\" href=\"/projects/#{@application.project.id}/applications\" data-method=\"post\" data-remote=\"true\" class=\"remote-#{@application.project.id}-applications btn btn-primary\">报名</a>" 
      }
    end
  end


  def setverified
    @application = Application.find(params[:id])
    if @application.update_attributes(:verified => !@application.verified)
      flash.now[:success] = 'application verified set successfully!'
      if @application.verified
        render :text => "<a href=\"/applications/setverified/#{@application.id}\" data-remote=\"true\" class = \"remote-setverified-#{@application.id}\">已通过，点击取消通过</a>"
      else
        render :text => "<a href=\"/applications/setverified/#{@application.id}\" data-remote=\"true\" class = \"remote-setverified-#{@application.id}\">未通过，点击审核通过</a>"
      end
    else  
      flash.now[:error] = 'fail to verify'
      render :text => "error_message_return:#{flash.now[:error]}"
    end
  end


  def setattended
    @application = Application.find(params[:id])
    if @application.update_attributes(:attended => !@application.attended)
      flash.now[:success] = 'application attended set successfully!'
      if @application.attended
        render :text => "<a href=\"/applications/setattended/#{@application.id}\" data-remote=\"true\" class = \"remote-setattended-#{@application.id}\">已签到，点击取消签到</a>"
      else
        render :text => "<a href=\"/applications/setattended/#{@application.id}\" data-remote=\"true\" class = \"remote-setattended-#{@application.id}\">未签到，点击完成签到</a>"
      end
    else  
      flash.now[:error] = 'fail to change attended'
      render :text => "error_message_return:#{flash.now[:error]}"
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_application
      @application = Application.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def application_params
      (params.permit(:project_id).empty?)? params.require(:application).permit(:project_id, :pickup_site_id) : params.permit(:project_id, :pickup_site_id)
    end
end

app/helpers/application_helper.rb
require 'open-uri'
module ApplicationHelper

  User::ADMIN = 0
  User::DIRECTOR = 1
  User::VOLUNTEER = 2
  def link_to_current(name, options = {}, html_options = {}, &block)
      link_to(name, options, html_options.merge((current_page?(options))? {id: 'current'}:{}), &block)
  end

  def current_user
    session[:current_user_id] && User.find_by_id(session[:current_user_id])
  end


  def get_all_directors_as_options(nursing_home = nil)
    if nursing_home.nil?
      @directors=User.where("user_type = ?", User::DIRECTOR)
    else
      @directors = nursing_home.directors
    end
    get_attrs_as_options(@directors, "name")
  end

#该方法不安全，需要注意。arr 是对象数组，attr_name是要调用的对象方法，输出二维数组
#该方法可以改用collection_select 替换，避免用send函数
  def get_attrs_as_options(arr, attr_name)
    arr.map{|a| [a.send(attr_name), a.id]}
  end

end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/views/applications/_form.html.erb
<%= form_for(@application) do |f| %>
  <% if @application.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@application.errors.count, "error") %> prohibited this application from being saved:</h2>

      <ul>
      <% @application.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :project_id, "选择活动：" %><br />
    <%= f.select :project_id, get_attrs_as_options(Project.published, "name") %>
  </div>

<!--
  <div class="field">
    <%#= f.label :verified %><br>
    <%#= f.check_box :verified %>
  </div>
  <div class="field">
    <%#= f.label :attended %><br>
    <%#= f.check_box :attended %>
  </div>
-->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/applications/edit.html.erb
<h1>Editing application</h1>

<%= render 'form' %>

<%= link_to 'Show', @application %> |
<%= link_to 'Back', applications_path %>

app/views/applications/index.html.erb
<h1>Listing applications</h1>

<table>
  <thead>
    <tr>
      <th>活动名称</th>
      <th>申请人</th>
      <th>是否通过</th>
      <th>是否参加</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @applications.each do |application| %>
      <tr>
        <td><%= application.project.name %></td>
        <td><%= application.volunteer.name %></td>
        <% if application.verified == false %>
          <td><%= link_to '未通过，点击审核通过', "/applications/setverified/#{application.id}", :remote => true, :class => "remote-setverified-#{application.id}" %></td>
        <% else %>
          <td><%= link_to '已通过，点击取消通过', "/applications/setverified/#{application.id}", :remote => true, :class => "remote-setverified-#{application.id}" %></td>
        <% end %>

        <% if application.attended == false %>
          <td><%= link_to '未签到，点击完成签到', "/applications/setattended/#{application.id}", :remote => true, :class => "remote-setattended-#{application.id}" %></td>
        <% else %>
          <td><%= link_to '已签到，点击取消签到', "/applications/setattended/#{application.id}", :remote => true, :class => "remote-setattended-#{application.id}" %></td>
        <% end %>

        <td><%= link_to 'Show', application %></td>
        <td><%= link_to 'Edit', edit_application_path(application) %></td>
        <td><%= link_to 'Destroy', application, method: :delete, data: { confirm: 'Are you sure?' } %></td>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Application', new_application_path %>

app/views/applications/new.html.erb
<h1>New application</h1>

<%= render 'form' %>

<%= link_to 'Back', applications_path %>

app/views/applications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Project:</strong>
  <%= @application.project.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @application.volunteer.name %>
</p>

<p>
  <strong>Verified:</strong>
  <%= @application.verified %>
</p>

<p>
  <strong>Attended:</strong>
  <%= @application.attended %>
</p>

<%= link_to 'Edit', edit_application_path(@application) %> |
<%= link_to 'Back', applications_path %>