config/routes.rb
Rails.application.routes.draw do

  get 'applications/setverified/:id' => 'applications#setverified'
  get 'applications/setattended/:id' => 'applications#setattended'
  get 'users/settype/:id' => 'users#settype'
  get '/projects/:id/direction' => 'projects#direction'
  get '/projects/:id/notice' => 'projects#notice'
  get 'users/check_available' => 'users#check_available'
  post '/user/login' => 'user#login'
  get '/user/logout' => 'user#logout'
  get '/user/manage' => 'user#manage'
  get '/residents/manage' => 'residents#manage'
  get '/projects/manage' => 'projects#manage'
  get '/nurses/manage' => 'nurses#manage'
  get '/users/manage' => 'users#manage'
  root :to => 'user#index'

  resources :pickup_sites, :residents, :nurses
  resources :rooms do
    resources :residents
  end
  resources :zones do
    resources :rooms
    resources :residents
  end

  resources :assignments, :records, :managements, :nursings, :applications 

  resources :projects do
    resources :applications, :assignments, :records
  end

  resources :nursing_homes do
    resources :managements, :projects, :zones, :rooms, :residents, :nurses, :nursings
  end

  resources :users do
    resources :applications, :messages
  end

  resources :messages

end

app/models/nursing_home.rb
class NursingHome < ActiveRecord::Base

  has_many :managements, dependent: :destroy
  has_many :directors, through: :managements, source: :user
  has_many :zones, dependent: :destroy
  has_many :rooms, through: :zones
  has_many :residents, through: :rooms
  has_many :projects
  has_many :records, through: :projects
  has_many :nurses
  has_many :nursings, through: :nurses
end

app/controllers/nursing_homes_controller.rb
class NursingHomesController < ApplicationController
  before_action :set_nursing_home, only: [:show, :edit, :update, :destroy]
  before_action :validate_set_rights, only: [:edit, :update]
  before_action :validate_admin_login, only: [:new, :create, :destroy]
  # GET /nursing_homes
  # GET /nursing_homes.json
  def index
    @nursing_homes = NursingHome.all
  end

  # GET /nursing_homes/1
  # GET /nursing_homes/1.json
  def show
  end

  # GET /nursing_homes/new
  def new
    @nursing_home = NursingHome.new
  end

  # GET /nursing_homes/1/edit
  def edit
  end

  # POST /nursing_homes
  # POST /nursing_homes.json
  def create
    @nursing_home = NursingHome.new(nursing_home_params)

    respond_to do |format|
      if @nursing_home.save
        format.html { redirect_to @nursing_home, notice: 'Nursing home was successfully created.' }
        format.json { render :show, status: :created, location: @nursing_home }
      else
        format.html { render :new }
        format.json { render json: @nursing_home.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nursing_homes/1
  # PATCH/PUT /nursing_homes/1.json
  def update
    respond_to do |format|
      if @nursing_home.update(nursing_home_params)
        format.html { redirect_to @nursing_home, notice: 'Nursing home was successfully updated.' }
        format.json { render :show, status: :ok, location: @nursing_home }
      else
        format.html { render :edit }
        format.json { render json: @nursing_home.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nursing_homes/1
  # DELETE /nursing_homes/1.json
  def destroy
    @nursing_home.destroy
    respond_to do |format|
      format.html { redirect_to nursing_homes_url, notice: 'Nursing home was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nursing_home
      @nursing_home = NursingHome.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nursing_home_params
      params.require(:nursing_home).permit(:name, :address, :contact, :phone_number, :description, :website)
    end

    def validate_set_rights
      unless (!current_user.nil? && ((current_user.director? && !current_user.nursing_homes.nil? && current_user.nursing_homes.map(&:id).include?(params[:id].to_i)) || current_user.admin?))
          respond_to do |format|
            format.html do
              if request.xhr?
                flash.now[:error]="抱歉，您权限不够！"
                render :text => "error_message_return:#{flash.now[:error]}"
              else
                flash[:error]="抱歉，您权限不够！"
                redirect_back_or_default
              end
            end
           format.json {render :text => ({:error=>flash[:error]}).to_json}
         end
       end
    end

end

app/helpers/nursing_homes_helper.rb
module NursingHomesHelper
end

app/views/nursing_homes/_form.html.erb
<%= form_for(@nursing_home) do |f| %>
  <% if @nursing_home.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nursing_home.errors.count, "error") %> prohibited this nursing_home from being saved:</h2>

      <ul>
      <% @nursing_home.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-xs-12 input-group form-group">
    <%= f.label :name, "名称：" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :address, "地址：" %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :contact, "联系人：" %><br>
    <%= f.text_field :contact %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :phone_number, "联系电话：" %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :description, "养老院介绍：" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :website, "网站：" %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions col-xs-12 input-group form-group">
    <%= f.submit "创建" %>
  </div>
<% end %>

app/views/nursing_homes/edit.html.erb
<h1>Editing nursing_home</h1>

<%= render 'form' %>

<%= link_to 'Show', @nursing_home %> |
<%= link_to 'Back', nursing_homes_path %>

app/views/nursing_homes/index.html.erb
<h4>养老院列表</h4>

<table>
  <thead>
    <tr>
      <th>名称</th>
      <th>地址</th>
      <th>养老院联系人</th>
      <th>联系电话</th>
      <th>介绍</th>
      <th>网站</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nursing_homes.each do |nursing_home| %>
      <tr>
        <td><%= nursing_home.name %></td>
        <td><%= nursing_home.address %></td>
        <td><%= nursing_home.contact %></td>
        <td><%= nursing_home.phone_number %></td>
        <td><%= nursing_home.description %></td>
        <td><%= nursing_home.website %></td>
        <td><%= link_to '查看', nursing_home %></td>
        <td><%= link_to '编辑', edit_nursing_home_path(nursing_home) %></td>
        <td><%= link_to '删除', nursing_home, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% nursing_home.managements.each do |management| %>
        <tr style="color:blue;">
          <td>组长：</td>
          <td><%= management.user.name %></td>
          <td><%= link_to '取消', management, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
      <tr style="font-size:12px;">
        <td><%= link_to '添加组长', new_nursing_home_management_path(nursing_home) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to '创建养老院', new_nursing_home_path %>

app/views/nursing_homes/new.html.erb
<div class="col-xs-11 row new_nurse background_grey">
  <h4>新建养老院</h4>
  <%= render 'form' %>
  <%= link_to '返回列表', nursing_homes_path %>
</div>

app/views/nursing_homes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nursing_home.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @nursing_home.address %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @nursing_home.contact %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @nursing_home.phone_number %>
</p>

<p>
  <strong>Description:</strong>
  <%= @nursing_home.description %>
</p>

<p>
  <strong>Website:</strong>
  <%= @nursing_home.website %>
</p>

<%= link_to 'Edit', edit_nursing_home_path(@nursing_home) %> |
<%= link_to 'Back', nursing_homes_path %>