config/routes.rb
Rails.application.routes.draw do

  get 'applications/setverified/:id' => 'applications#setverified'
  get 'applications/setattended/:id' => 'applications#setattended'
  get 'users/settype/:id' => 'users#settype'
  get '/projects/:id/direction' => 'projects#direction'
  get '/projects/:id/notice' => 'projects#notice'
  get 'users/check_available' => 'users#check_available'
  post '/user/login' => 'user#login'
  get '/user/logout' => 'user#logout'
  get '/user/manage' => 'user#manage'
  get '/residents/manage' => 'residents#manage'
  get '/projects/manage' => 'projects#manage'
  get '/nurses/manage' => 'nurses#manage'
  get '/users/manage' => 'users#manage'
  root :to => 'user#index'

  resources :pickup_sites, :residents, :nurses
  resources :rooms do
    resources :residents
  end
  resources :zones do
    resources :rooms
    resources :residents
  end

  resources :assignments, :records, :managements, :nursings, :applications 

  resources :projects do
    resources :applications, :assignments, :records
  end

  resources :nursing_homes do
    resources :managements, :projects, :zones, :rooms, :residents, :nurses, :nursings
  end

  resources :users do
    resources :applications, :messages
  end

  resources :messages

end

app/models/project.rb
class Project < ActiveRecord::Base
#活动报名截止时间为活动前一天晚上十点 project.start_at.beginning_of_day.ago(7200)

  belongs_to :nursing_home

  has_many :applications
  has_many :applicants, through: :applications, source: :user
  has_many :assignments,  dependent: :destroy
  has_many :records
  has_many :attended_applications, -> {where verified: true, attended: true}, class_name: "Application"
  has_many :volunteers, through: :attended_applications, source: :user
  belongs_to :contact, class_name: "User", foreign_key: "contact_id"
  has_many :pickup_sites
  accepts_nested_attributes_for :pickup_sites, allow_destroy: true, reject_if: lambda { |attributes| attributes['name'].blank? }

#活动状态定义（针对活动本身而言）
#1、尚未开始报名。活动虽然被已经被创建但是还没有对外发布，默认两周以内开始的活动为可以报名活动，
#超过两周以后才开始的活动只会被管理员看到。
#2、已经开始报名但尚未进行。对用户而言分为已经报名和尚未报名。
#3、报名已经结束，但尚未进行。对用户而言只有已经报名一个状态，如果未报名，看不到此类活动。
#4、正在进行。只有已经报名的用户才能看到。
#5、已经结束，即往期活动。对用户而言分为参加过的活动和未参加过的活动。
#注意：某个活动对于用户而言的状态都在User model中定义，例如已经报名的活动、参加过的活动等。
  scope :draft,      -> { where("start_at > ?", Time.now+14.days) }
#  scope :published
#  scope :upcoming
  scope :ongoing,    -> { where("start_at < ? AND end_at > ?", Time.now, Time.now) }
  scope :unfinished, -> { where("end_at > ?", Time.now) }
  scope :finished,   -> { where("end_at < ?", Time.now) }

#已经开始报名但尚未进行的活动
  def self.published
    if Time.now < Time.now.end_of_day.ago(7199)
      where("start_at > ? AND start_at < ?", Time.now.end_of_day, (Time.now+14.days))
    else
      where("start_at > ? AND start_at < ?", (Time.now.end_of_day+1.day), (Time.now+14.days))
    end
  end
#报名已经结束，但尚未进行的活动
  def self.upcoming
    if Time.now < Time.now.end_of_day.ago(7199)
      where("start_at > ? AND start_at < ?", Time.now, Time.now.end_of_day)
    else
      where("start_at > ? AND start_at < ?", Time.now, Time.now.end_of_day+1.day)
    end
  end

  def reg_deadline
    start_at.beginning_of_day.ago(7200)
  end

  def ongoing?
    start_at < Time.now && end_at > Time.now
  end



end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy, :direction,:notice]
  before_action :validate_director_login, only: [:new]
  before_action :validate_set_rights, only: [:edit, :create, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    if params[:nursing_home_id].nil?
      @draft_projects = Project.draft if !current_user.nil? && current_user.director?
      @published_projects = Project.published
      @upcoming_projects = current_user.upcoming_projects  unless current_user.nil?
      @ongoing_projects = current_user.ongoing_projects  unless current_user.nil?
      @unfinished_projects = current_user.unfinished_projects unless current_user.nil?
    else
      params[:offset] ||= 0
      params[:limit] ||= 1000
      @projects = NursingHome.find_by_id(params[:nursing_home_id]).projects.order("id desc").offset(params[:offset]).limit(params[:count])
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  # 代码存在bug，有待修复 TO DO
  def update 
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  def direction
  end

  def notice
  end

  def manage
    @projects = Project.unfinished.where(:nursing_home_id => current_user.nursing_homes)
    @finished_projects = Project.finished.where(:nursing_home_id => current_user.nursing_homes)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :nursing_home_id, :description, :start_at, :end_at, :staff_number, :contact_id, pickup_sites_attributes: [:id, :name, :project_id, :liaison, :phone_number, :meeting_time, :_destroy])
    end

    def validate_set_rights
      unless (!current_user.nil? && ((current_user.director? && !current_user.nursing_homes.empty? && current_user.nursing_homes.map(&:id).include?(@project.nil?? params[:project][:nursing_home_id].to_i : @project.nursing_home_id) ) || current_user.admin?))
          respond_to do |format|
            format.html do
              if request.xhr?
                flash.now[:error]="抱歉，您权限不够！"
                render :text => "error_message_return:#{flash.now[:error]}"
              else
                flash[:error]="抱歉，您权限不够！"
                redirect_back_or_default
              end
            end
           format.json {render :text => ({:error=>flash[:error]}).to_json}
         end
       end
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field col-xs-12 input-group form-group">
    <%= f.label :name, "活动名称：" %><br>
    <%= f.text_field :name %>
  </div>

  <div class="field col-xs-12 input-group form-group">
    <%= f.label :nursing_home_id, "选择养老院：" %><br />
    <%= f.select :nursing_home_id, get_attrs_as_options(current_user.nursing_homes, "name") %>
  </div>

  <div class="field col-xs-12 input-group form-group"><!-- description中应该包含集合地点、注意事项、鼓励话语等-->
    <%= f.label :description, "活动介绍：" %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :start_at, "开始时间：" %><br>
    <%= f.datetime_select(:start_at) %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :end_at, "结束时间：" %><br>
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field col-xs-12 input-group form-group">
    <%= f.label :staff_number, "预计需要人数：" %><br>
    <%= f.number_field :staff_number %>
  </div>

  <div class="field col-xs-12 input-group form-group">
    <%= f.label :contact_id, "选择联系人：" %><br>
    <%= f.select :contact_id, get_all_directors_as_options %>
  </div>

    <%= f.fields_for :pickup_sites, @project.pickup_sites do |pickup_site| %>
    <div class="field col-xs-12 input-group form-group background_grey">
      集合地点:<br> <%= pickup_site.text_field :name %><br>
      集合时间:<br> <%= pickup_site.datetime_select :meeting_time %><br>
      接站人:<br> <%= pickup_site.text_field :liaison %><br>
      联系电话:<br> <%= pickup_site.text_field :phone_number %><br>
      <%= pickup_site.label :_destroy, '勾选删除:' %>  
      <%= pickup_site.check_box :_destroy %>  
    </div>
    <% end %>
  <!-- 此处需要添加自动补全 TO DO -->
  <div class="field multiupload col-xs-12 input-group form-group">
    <%= f.fields_for :pickup_sites, @project.pickup_sites.build do |pickup_site| %>
      <%= pickup_site.hidden_field :id %>
      集合地点:<br> <%= pickup_site.text_field :name %><br>
      集合时间:<br> <%= pickup_site.datetime_select :meeting_time %><br>
      接站人:<br> <%= pickup_site.text_field :liaison %><br>
      联系电话:<br> <%= pickup_site.text_field :phone_number %><br>
    <% end %>
    <span class="glyphicon glyphicon-remove-circle"></span>点击取消创建该接站点
  </div>


  <div class="actions  col-xs-12 input-group form-group">
    <%= f.submit "提 交"%>
  </div>
<% end %>

app/views/projects/_show.html.erb
  <% @project = project if defined? project %>
  <div class="col-xs-11 row reg_project">
    <div class="tag">
      <img src="/images/tag-orange.png" class="img-responsive" alt="ichina tag-orange">
      <div class=tag-label>
        <p>正在</p>
        <p>报名</p>
      </div>
    </div>

    <div class="desc">
      <p>
        <%= l(@project.start_at,format: :date) %>
        <%= l(@project.start_at,format: :week) %>
      </p>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>
      <p>
        <%= @project.name %>
      </p>
      <div class="toggle_btn">
        <span class="rotate glyphicon glyphicon-backward" aria-hidden="true"></span>
      </div>
    </div>
    <div class="text" style="display:none">
      <hr class="division">
      <p><关怀活动报名></p>
      <p>时间: <%= l(@project.start_at,format: :date_week) %>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>

      <p>地点: <%= @project.nursing_home.name %></p>
      <p>报名方式:点击下方按钮报名</p>
      <p>报名截止时间: <%= l(@project.reg_deadline ,format: :short)%></p>


      <p>联络人: <%= @project.contact.name+' '+@project.contact.phone_number %> </p>
      <p>
        <%= @project.description %>
      </p>
    </div>

    <div class="operations">
      <div>
        <% unless (current_user && current_user.has_applied?(@project)) %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            报名
          </button>
        <% else %>
          <% @application = current_user.application_of(@project) %>
          <%= link_to '取消报名', "/applications/#{@application.id}", method: :delete, :remote => true, :class => "remote-applications-#{@application.id} btn btn-primary" %>
          <%= link_to '查看报名信息', "/projects/#{@project.id}/direction", class: "btn btn-danger" %>
        <% end %>

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
          <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">请选择接车地点：</h4>
              </div>
              <%= form_for @project.applications.build, remote: false do |f| %>
                <div class="modal-body">
                  <div class="field">
                    <%= f.hidden_field :project_id, value: @project.id%>
                    <%= f.select :pickup_site_id, get_attrs_as_options(@project.pickup_sites, "name") %>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                  <%= f.submit "报名", class: "btn btn-primary"%>
                </div>
              <% end %>
            </div>
          </div>
        </div>

      </div>
      <div> </div>
    </div>
  </div>

app/views/projects/_show_draft.html.erb
  <% @project = project if defined? project %>
  <div class="reg_project col-xs-11 row">
    <div class="tag">
      <img src="../images/tag-orange.png" class="img-responsive" alt="ichina tag-orange">
      <div class=tag-label>
        <p>尚未</p>
        <p>报名</p>
      </div>
    </div>
    <div class="desc">
      <p>
        <%= l(@project.start_at,format: :date) %>
        <%= l(@project.start_at,format: :week) %>
      </p>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>
      <p>
        <%= @project.name %>
      </p>
      <div class="toggle_btn">
        <span class="rotate glyphicon glyphicon-backward" aria-hidden="true"></span>
      </div>
    </div>
    <div class="text" style="display:none">
      <hr class="division">
      <p><关怀活动报名></p>
      <p>时间: <%= l(@project.start_at,format: :date_week) %>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>

      <p>地点: <%= @project.nursing_home.name %></p>
      <p>报名开始时间: <%= l(@project.start_at-14.days ,format: :short)%></p>
      <p>报名截止时间: <%= l(@project.reg_deadline ,format: :short)%></p>

      <p>联络人: <%= @project.contact.name+' '+@project.contact.phone_number %> </p>
      <p>
        <%= @project.description %>
      </p>
    </div>
  </div>

app/views/projects/_show_unfinished.html.erb
  <% @project = project if defined? project %>
  <div class="col-xs-11 row reg_project">
    <div class="tag">
      <img src="../images/tag-grey.png" class="img-responsive" alt="ichina tag-orange">
      <div class=tag-label>
        <p>活动</p>
        <p>结束</p>
      </div>
    </div>
    <div class="desc">
      <p>
        <%= l(@project.start_at,format: :date) %>
        <%= l(@project.start_at,format: :week) %>
      </p>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>
      <p>
        <%= @project.name %>
      </p>
      <div class="toggle_btn">
        <span class="rotate glyphicon glyphicon-backward" aria-hidden="true"></span>
      </div>
    </div>
    <div class="text" style="display:none">
      <hr class="division">
      <p><关怀活动报名></p>
      <p>时间: <%= l(@project.start_at,format: :date_week) %>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>

      <p>地点: <%= @project.nursing_home.name %></p>
      <p>报名截止时间: <%= l(@project.reg_deadline ,format: :short)%></p>


      <p>联络人: <%= @project.contact.name+' '+@project.contact.phone_number %> </p>
      <p>
        <%= @project.description %>
      </p>
    </div>
    <div class="operations"><!-- TO DO -->
      <div>
        <%= link_to '感谢您参加此次活动,请填写关怀记录!', "/projects/#{@project.id}/records/new", class: "btn btn-danger" %>
      </div>
    </div>
  </div>

app/views/projects/_show_upcoming_and_ongoing.html.erb
  <% @project = project if defined? project %>
  <div class="col-xs-11 row reg_project">
    <div class="tag">
      <img src="../images/tag-grey.png" class="img-responsive" alt="ichina tag-orange">
      <div class=tag-label>
        <p>报名</p>
        <p>结束</p>
      </div>
    </div>
    <div class="desc">
      <p>
        <%= l(@project.start_at,format: :date) %>
        <%= l(@project.start_at,format: :week) %>
      </p>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>
      <p>
        <%= @project.name %>
      </p>
      <div class="toggle_btn">
        <span class="rotate glyphicon glyphicon-backward" aria-hidden="true"></span>
      </div>
    </div>
    <div class="text" style="display:none">
      <hr class="division">
      <p><关怀活动报名></p>
      <p>时间: <%= l(@project.start_at,format: :date_week) %>
      <p>
        <%=  l(@project.start_at,format: :am_pm)+"："+l(@project.start_at,format: :day_time)+"-"+l(@project.end_at,format: :day_time) %>
      </p>

      <p>地点: <%= @project.nursing_home.name %></p>
      <p>报名截止时间: <%= l(@project.reg_deadline ,format: :short)%></p>


      <p>联络人: <%= @project.contact.name+' '+@project.contact.phone_number %> </p>
      <p>
        <%= @project.description %>
      </p>
    </div>
    <div class="operations">
      <div>
        <% if current_user.has_be_assigned?(@project) %>
          <%= link_to '查看组长分配关怀对象', zone_residents_path(current_user.assignment_of(@project).zone), class: "btn btn-danger" %>
        <% else %>
          <%= link_to '查看报名信息', "/projects/#{@project.id}/direction", class: "btn btn-danger" %>
        <% end %>
      </div>
    </div>
  </div>

app/views/projects/direction.html.erb
<div class="col-xs-11 row ">

<% unless current_user.has_be_assigned?(@project) %>
  <h1>欢迎参加爱中国志愿者关怀活动!</h1>
  <p>
    欢迎您报名参加<%= l(@project.start_at, format: :date_week)+" "+l(@project.start_at,format: :am_pm)+" "+@project.nursing_home.name %>的生命关怀志愿服务,请等待组长分配您在<%= @project.nursing_home.name %>的关怀区域和关怀对象,请在<%= l(@project.start_at.days_ago(2), format: :day) %>之后来此查看相关信息。
  </p>
<% else %>
  <h1>感谢参加爱中国志愿者关怀活动!</h1>
  <p>
    感谢您报名参加<%= l(@project.start_at, format: :date_week)+" "+l(@project.start_at,format: :am_pm)+" "+@project.nursing_home.name %>的生命关怀志愿服务,请查看组长分配您在<%= @project.nursing_home.name %>的关怀区域和关怀对象。
  </p>
<% end %>


<p>以下信息帮助您做好关怀前的准备工作:</p>
<h2>
  <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
  <a href="http://mp.weixin.qq.com/s?__biz=MjM5OTQ1Mzg0Nw==&mid=209275422&idx=1&sn=6e36d067831847e183e0401e20b9ebbd&scene=18#wechat_redirect">初次关怀指南</a>
</h2>
<p>在每次参加关怀活动之前,请仔细阅读:</p>
<h2>
  <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
  <a href="#">志愿者关怀行为规范</a>
</h2>
<p>您还可以了解本次活动需要关怀的老人们:</p>
<h2>
  <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
  <% if current_user.has_be_assigned?(@project) %>
    <%= link_to "查看组长已分配关怀对象", zone_residents_path(current_user.assignment_of(@project).zone) %>
  <% else %>
    <%= link_to "查看需要关怀的老人", nursing_home_residents_path(@project.nursing_home) %>
  <% end %>
</h2>
<p>想了解过去的关怀活动风采:</p>
<h2>
  <span class="glyphicon glyphicon-hand-right" aria-hidden="true"></span>
  <a href="http://weixin.sogou.com/gzhwap?openid=oIWsFt_bZs7H1FvcTQeQePzDjZ2I">往期活动风采</a>
</h2>
</div>

app/views/projects/edit.html.erb
  <div class="col-xs-11 row reg_project">
    <h4>修改活动信息</h4>

    <%= render 'form' %>
  </div>

app/views/projects/index.html.erb
<div id="project_show" class="">

  <% if defined? @draft_projects %>
    <% @draft_projects.each do |project| %>
      <%= render partial: "show_draft", locals: {project: project, type: "draft"} %>
    <% end %>
  <% end %>

  <% if defined? @published_projects %>
    <% @published_projects.each do |project| %>
      <%= render partial: "show", locals: {project: project, type: "published"} %>
    <% end %>
  <% end %>


  <% if defined? @upcoming_projects %>
    <% @upcoming_projects.each do |project| %>
      <%= render partial: "show_upcoming_and_ongoing", locals: {project: project, type: "upcoming"} %>
    <% end %>
  <% end %> 

  <% if defined? @ongoing_projects %>
    <% @ongoing_projects.each do |project| %>
      <%= render partial: "show_upcoming_and_ongoing", locals: {project: project, type: "ongoing"} %>
    <% end %>
  <% end %>

  <% if defined? @unfinished_projects %>
    <% @unfinished_projects.each do |project| %>
      <%= render partial: "show_unfinished", locals: {project: project, type: "unfinished"} %>
    <% end %>
  <% end %>
</div>

app/views/projects/manage.html.erb
<% @finished_projects.each do |project| %>
  <div class="col-xs-11 row reg_project">
    <div class="desc">
      <p>
        <%= l(project.start_at,format: :date) %>
        <%= l(project.start_at,format: :week) %>
      </p>
      <p>
        <%=  l(project.start_at,format: :am_pm)+"："+l(project.start_at,format: :day_time)+"-"+l(project.end_at,format: :day_time) %>
      </p>
      <p>
        <%= project.name %>
      </p>
    </div>

    <div class="operations">
      <div>
        <%= link_to '处理签到', project_applications_path(project), class: "col-xs-12 btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>




<% @projects.each do |project| %>
  <div class="col-xs-11 row reg_project">
    <div class="desc">
      <p>
        <%= l(project.start_at,format: :date) %>
        <%= l(project.start_at,format: :week) %>
      </p>
      <p>
        <%=  l(project.start_at,format: :am_pm)+"："+l(project.start_at,format: :day_time)+"-"+l(project.end_at,format: :day_time) %>
      </p>
      <p>
        <%= project.name %>
      </p>
      <div class="toggle_btn">
        <span class="rotate glyphicon glyphicon-backward" aria-hidden="true"></span>
      </div>
    </div>
    <div class="text" style="display:none">
      <hr class="division">
      <p><关怀活动报名></p>
      <p>时间: <%= l(project.start_at,format: :date_week) %>
      <p>
        <%=  l(project.start_at,format: :am_pm)+"："+l(project.start_at,format: :day_time)+"-"+l(project.end_at,format: :day_time) %>
      </p>

      <p>地点: <%= project.nursing_home.name %></p>
      <p>报名方式:点击下方按钮报名</p>
      <p>报名截止时间: <%= l(project.reg_deadline ,format: :short)%></p>


      <p>联络人: <%= project.contact.name+' '+project.contact.phone_number %> </p>
      <p>
        <%= project.description %>
      </p>
    </div>

    <div class="operations">
      <div>
        <% if project.ongoing? %>
          <%= link_to '处理签到', project_applications_path(project), class: "col-xs-12 btn btn-primary" %>
        <% else %>
          <%= link_to '修改活动', edit_project_path(project), class: "col-xs-5 btn btn-primary" %>
          <%= link_to '取消活动', project, method: :delete, data: { confirm: '确认取消?' }, class: "col-xs-5 col-xs-offset-2 btn btn-primary" %>
        <% end %>
      </div>


    </div>

    <div class="operations">
      <% unless project.applicants.empty? %>
        <h4>已报名的志愿者：</h4>
      <% end %>
      <table class="table table-bordered">
      <% project.applicants.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.phone_number %></td>
          <td>
            <%= link_to '查看', user, class: "btn btn-primary btn-sm" %>
            <% if user.has_be_assigned?(project) %>
              <% @assignment = user.assignment_of(project) %>
            <% else %>
              <% @assignment = project.assignments.build %>
              <% @assignment.user_id = user.id %>
            <% end %>

            <%= form_for(@assignment, html: {class: "inline_form"}) do |f| %>
              <% if @assignment.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@assignment.errors.count, "error") %> prohibited this assignment from being saved:</h2>
                  <ul>
                  <% @assignment.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field" style="display: none">
                <%= f.number_field :user_id %>
              </div>
              <div class="field" style="display: none">
                <%= f.number_field :project_id %>
              </div>

              <%= f.select :zone_id, project.nursing_home.zones.collect{|z| [z.name, z.id]}, {include_blank: "分配区域"} %>
              <%= f.submit (user.has_be_assigned?(project)? "更新":"分配") %>
            <% end %>

          </td>
        </tr>
      <% end %>
      </table>
    </div>
  </div>
<% end %>

  <div class="col-xs-11 row reg_project background_grey">
    <div>
      <hr class="division">
    </div>
  
    <div class="operations">
      <div class="">
        <%= link_to '创建活动', "/projects/new", class: "col-xs-12 btn btn-primary" %>
      </div>
    </div>

  </div>

app/views/projects/show.html.erb
<!--
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Nursing home:</strong>
  <%= @project.nursing_home_id %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start at:</strong>
  <%= @project.start_at %>
</p>

<p>
  <strong>End at:</strong>
  <%= @project.end_at %>
</p>

<p>
  <strong>Staff number:</strong>
  <%= @project.staff_number %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @project.contact_id %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>
-->

<%= render "show" %>