config/routes.rb
Rails.application.routes.draw do

  get 'applications/setverified/:id' => 'applications#setverified'
  get 'applications/setattended/:id' => 'applications#setattended'
  get 'users/settype/:id' => 'users#settype'
  get '/projects/:id/direction' => 'projects#direction'
  get '/projects/:id/notice' => 'projects#notice'
  get 'users/check_available' => 'users#check_available'
  post '/user/login' => 'user#login'
  get '/user/logout' => 'user#logout'
  get '/user/manage' => 'user#manage'
  get '/residents/manage' => 'residents#manage'
  get '/projects/manage' => 'projects#manage'
  get '/nurses/manage' => 'nurses#manage'
  get '/users/manage' => 'users#manage'
  root :to => 'user#index'

  resources :pickup_sites, :residents, :nurses
  resources :rooms do
    resources :residents
  end
  resources :zones do
    resources :rooms
    resources :residents
  end

  resources :assignments, :records, :managements, :nursings, :applications 

  resources :projects do
    resources :applications, :assignments, :records
  end

  resources :nursing_homes do
    resources :managements, :projects, :zones, :rooms, :residents, :nurses, :nursings
  end

  resources :users do
    resources :applications, :messages
  end

  resources :messages

end

app/models/management.rb
class Management < ActiveRecord::Base
  belongs_to :user
  belongs_to :director, class_name: "User", foreign_key: "user_id"
  belongs_to :nursing_home
end

app/controllers/managements_controller.rb
class ManagementsController < ApplicationController
  before_action :set_management, only: [:show, :edit, :update, :destroy]
  before_action :validate_admin_login
  # GET /managements
  # GET /managements.json
  def index
    if params[:nursing_home_id].nil?
      @managements = Management.all
    else
      params[:offset] ||= 0
      params[:limit] ||= 1000
      @managements = NursingHome.find_by_id(params[:nursing_home_id]).managements.order("id desc").offset(params[:offset]).limit(params[:count])
    end
  end

  # GET /managements/1
  # GET /managements/1.json
  def show
  end

  # GET /managements/new
  def new
    @management = Management.new
  end

  # GET /managements/1/edit
  def edit
  end

  # POST /managements
  # POST /managements.json
  def create
    @management = Management.new(management_params)

    respond_to do |format|
      if @management.save
        format.html { redirect_to @management, notice: 'Management was successfully created.' }
        format.json { render :show, status: :created, location: @management }
      else
        format.html { render :new }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /managements/1
  # PATCH/PUT /managements/1.json
  def update
    respond_to do |format|
      if @management.update(management_params)
        format.html { redirect_to @management, notice: 'Management was successfully updated.' }
        format.json { render :show, status: :ok, location: @management }
      else
        format.html { render :edit }
        format.json { render json: @management.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /managements/1
  # DELETE /managements/1.json
  def destroy
    @management.destroy
    respond_to do |format|
      format.html { redirect_to managements_url, notice: 'Management was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_management
      @management = Management.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def management_params
      params.require(:management).permit(:nursing_home_id, :user_id)
    end
end

app/helpers/managements_helper.rb
module ManagementsHelper


end

app/views/managements/_form.html.erb
<%= form_for(@management) do |f| %>
  <% if @management.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@management.errors.count, "error") %> prohibited this management from being saved:</h2>

      <ul>
      <% @management.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nursing_home_id, "选择养老院：" %><br />
    <%= f.collection_select :nursing_home_id, NursingHome.all, :id, :name %>
  </div>

  <div class="field">
    <%= f.label :user_id, "选择管理员" %><br>
    <%= f.select :user_id, get_all_directors_as_options %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/managements/edit.html.erb
<h1>Editing management</h1>

<%= render 'form' %>

<%= link_to 'Show', @management %> |
<%= link_to 'Back', managements_path %>

app/views/managements/index.html.erb
<h1>Listing managements</h1>

<table>
  <thead>
    <tr>
      <th>Nursing home</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @managements.each do |management| %>
      <tr>
        <td><%= management.nursing_home.name %></td>
        <td><%= management.director.name%></td>
        <td><%= link_to 'Show', management %></td>
        <td><%= link_to 'Edit', edit_management_path(management) %></td>
        <td><%= link_to 'Destroy', management, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Management', new_management_path %>

app/views/managements/new.html.erb
<h1>New management</h1>

<%= render 'form' %>

<%= link_to 'Back', managements_path %>

app/views/managements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nursing home:</strong>
  <%= @management.nursing_home_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @management.user_id %>
</p>

<%= link_to 'Edit', edit_management_path(@management) %> |
<%= link_to 'Back', managements_path %>